name: Backend CI

on:
  push:
    paths:
      - "backends/**"
      - "docs/**"
      - ".github/workflows/backend.yml"
  pull_request:
    paths:
      - "backends/**"
      - "docs/**"
      - ".github/workflows/backend.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backends
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Lint
        run: uv run ruff check
      - name: Tests
        run: uv run pytest
